- hosts: localhost
  tasks:
    # dotfiles get put in their place
    - name: install stow
      homebrew:
        name: stow
    - name: cloning dotfiles
      ansible.builtin.git:
        repo: 'git@github.com:mrr11k/dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: master
    - name: stow dotfiles
      shell: cd $HOME/dofiles && ./macos




